#!/usr/bin/env python3
"""Recompute the hard-negative matched-pair comparison from the trace grid.

usM1's W1/W2 reply reports a matched cross-boundary comparison of risky vs.
hard-negative canaries within the same tasks, with Wilson 95% CIs. The pair
count (108) and the two 1-decimal point rates (risky 25.9%, hard-neg 20.4%)
come from the twoByTwoCross* macros; the integer success counts (28, 22) are
not emitted as macros, so they are back-derived from the rounded percentages
and verified unique (see _unique_count_for_pct). The reported CI endpoints must
also come from a real computation. This script derives all five numbers (n,
both point rates, both Wilson intervals) from that single macro source and
emits a JSON artifact so the reviewer-facing values are reproducible rather
than hand-typed.

Wilson score interval (no continuity correction) is the frozen method — the
same estimator `estimate_recall.py` uses for its detector-miss prevalence, so
the benchmark reports one CI convention throughout.

Usage:
  PYTHONPATH=src python scripts/compute_hard_negative_ci.py \\
      [--out results/hard_negative_analysis/hard_negative_ci.json]

The pair counts are read from the twoByTwo* macros in paper/results_macros.tex
(themselves generated by generate_results_macros.py from the trace grid), so
this script never re-hardcodes them; it only attaches the CI computation.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
import re
from pathlib import Path
from typing import Dict, Tuple

_Z95 = 1.959963984540054  # two-sided 95% normal quantile


def wilson_interval(k: int, n: int, z: float = _Z95) -> Tuple[float, float]:
    """Wilson score 95% interval for a binomial proportion k/n (no CC)."""
    if n == 0:
        return (0.0, 0.0)
    p = k / n
    denom = 1.0 + z * z / n
    center = p + z * z / (2.0 * n)
    margin = z * math.sqrt(p * (1.0 - p) / n + z * z / (4.0 * n * n))
    return ((center - margin) / denom, (center + margin) / denom)


def _read_macro_int(macros_text: str, name: str) -> int:
    m = re.search(r"\\newcommand\{\\" + re.escape(name) + r"\}\{([-\d.]+)\}",
                  macros_text)
    if not m:
        raise ValueError(f"macro {name} not found in results_macros.tex")
    return int(round(float(m.group(1))))


def _read_macro_float(macros_text: str, name: str) -> float:
    m = re.search(r"\\newcommand\{\\" + re.escape(name) + r"\}\{([-\d.]+)\}",
                  macros_text)
    if not m:
        raise ValueError(f"macro {name} not found in results_macros.tex")
    return float(m.group(1))


def _unique_count_for_pct(pct: float, n: int, macro_name: str) -> int:
    """Back-derive the integer success count from a 1-decimal percentage.

    The macro layer emits only the rounded percentage, so we invert it. Return
    the unique k in [0, n] whose (k/n*100) rounds to `pct` at 1 decimal. Raise
    if zero or more than one k qualifies -- an ambiguous derivation must not be
    silently guessed.
    """
    candidates = [k for k in range(n + 1)
                  if round(k / n * 100.0, 1) == round(pct, 1)]
    if len(candidates) != 1:
        raise ValueError(
            f"back-derivation of {macro_name}={pct} over n={n} is not unique: "
            f"candidates={candidates}. Emit a count macro instead of relying "
            f"on the rounded percentage.")
    return candidates[0]


def compute(repo_root: Path) -> Dict[str, object]:
    macros_path = repo_root / "paper/results_macros.tex"
    macros_text = macros_path.read_text(encoding="utf-8")

    n_pairs = _read_macro_int(macros_text, "twoByTwoCrossN")
    risky_pct = _read_macro_float(macros_text, "twoByTwoCrossProd")
    hardneg_pct = _read_macro_float(macros_text, "twoByTwoCrossPlac")

    # The macro layer emits only the 1-decimal percentage, not the raw success
    # count, so we back-derive the integer count and then VERIFY the derivation
    # is unique: exactly one integer k in [0, n] must round to the stated
    # percentage at 1 decimal. If two counts could round to it, the derivation
    # is ambiguous and we refuse rather than guess.
    risky_k = _unique_count_for_pct(risky_pct, n_pairs, "twoByTwoCrossProd")
    hardneg_k = _unique_count_for_pct(hardneg_pct, n_pairs, "twoByTwoCrossPlac")

    risky_lo, risky_hi = wilson_interval(risky_k, n_pairs)
    hn_lo, hn_hi = wilson_interval(hardneg_k, n_pairs)

    payload = {
        "method": "wilson_score_95_no_continuity_correction",
        "z_95": _Z95,
        "source": "paper/results_macros.tex twoByTwoCross* macros",
        "successes_derivation": "back_derived_from_rounded_pct",
        "successes_derivation_note": (
            "count macros are not emitted; success counts are inverted from "
            "the 1-decimal percentage macros and verified unique via "
            "_unique_count_for_pct"),
        "n_pairs": n_pairs,
        "risky": {
            "successes": risky_k,
            "rate_pct": round(risky_k / n_pairs * 100.0, 1),
            "wilson_ci95_pct": [round(risky_lo * 100.0, 1),
                                round(risky_hi * 100.0, 1)],
        },
        "hard_negative": {
            "successes": hardneg_k,
            "rate_pct": round(hardneg_k / n_pairs * 100.0, 1),
            "wilson_ci95_pct": [round(hn_lo * 100.0, 1),
                                round(hn_hi * 100.0, 1)],
        },
    }
    payload["input_hash"] = hashlib.sha256(
        f"{n_pairs}|{risky_k}|{hardneg_k}".encode()).hexdigest()
    return payload


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--repo-root", default=".")
    ap.add_argument(
        "--out",
        default="results/hard_negative_analysis/hard_negative_ci.json")
    args = ap.parse_args()
    root = Path(args.repo_root).resolve()

    payload = compute(root)
    out = root / args.out
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(payload, indent=2, ensure_ascii=False),
                   encoding="utf-8")

    r = payload["risky"]
    h = payload["hard_negative"]
    print(f"n_pairs = {payload['n_pairs']}")
    print(f"risky      {r['successes']}/{payload['n_pairs']} = "
          f"{r['rate_pct']}%  Wilson95 {r['wilson_ci95_pct']}")
    print(f"hard-neg   {h['successes']}/{payload['n_pairs']} = "
          f"{h['rate_pct']}%  Wilson95 {h['wilson_ci95_pct']}")
    print(f"-> {args.out}")


if __name__ == "__main__":
    main()
